### ISSUE TITLE
TODO list 2021-12-22

### ISSUE THREAD

**Issue by snotskie** [EducationalSciences693/ShadowspectCodeRules#1]
- [x] don't make the script automatically run all codes in a for loop. make a helper, make it easy to specify which you want, but don't do them automatically
- [x] when you ask it to populate a training set for a code, also add the id's for that set to the training.yaml file
- [x] fix the session #5 nan problem in the dataset
- [ ] track down what the correct index for those nan's in the training.yaml should be. shouldn't be too hard, i can ctrl+f in the big spreadsheet, and there's only like 5 total i need to do that to
- [x] pre-process the data to remove extra newlines in all turns of talk, that way we can import into Cody sensibly
